### PR TITLE
update replay script for break-apart-ability and tri-pickle uploads

### PR DESCRIPTION
**Pull request by mochic**
update replay script

### CODE REVIEW

**Comment by mochic** [comment]
@jeromelecoq hey could you please review this for me?
-Chris

**Review by jeromelecoq — CHANGES_REQUESTED** [review]
- It bothers me that scripts are now pulled from a separate repos in ophys and ephys. 
- what is the rationale for the change of padding?

**Comment by mochic** [comment]
1. While it is different from some regimens I don’t think that this is much different. What are your concerns?
2. As per Corbett’s request, he wanted pre-experiment time to display the desktop and not the gray screen.

**Comment by jeromelecoq** [comment]
1/ We can have two repos that have the same scripts but divergent code and the code would never merge with one another + it is harder to know where things are. Why does pipeline behavior work would be pulled from a single person repo? What if your personal account is deleted? 
2/ This will change the mouse experience, no?

**Comment by mochic** [comment]
1. I think that trying to maintain a single script is unnecessary overhead for what we would get out of that. We would prefer to be able to rapidly iterate and add/tweak DoC features/implementations to better fit our needs without having to support previous functionality or worry about breaking old functionality, etc. The account thing is true but I don't think it's a very likely situation.
2. I assume so but I'm just doing what Corbett wants.

**Pull request closed without merging**
