### PR TITLE
update replay/DoC scripts

### PR DESCRIPTION
**Pull request by mochic**
Updates replay script:
- upload a tri-pickle
- allow for individual portions of the replay session to be played separably
Extends functionality of DoC script being used.

### CODE REVIEW

**Comment by mochic** [comment]
@jeromelecoq 
Hey I made the changes you asked for. Can you please review this now?

**Comment by mochic** [comment]
@jeromelecoq 
Hey, I've made a couple new changes and I think this is what we want to have committed for our first 1.0.0 version of the regimen.

**Comment by mochic** [comment]
@jeromelecoq
hey can you please review this? ive incorporated changes made by corbett.

**Review by jeromelecoq — APPROVED** [review]
looks good

**Pull request merged**
