### PR TITLE
added stage for recording with image set B

### PR DESCRIPTION
**Pull request by corbennett**

### CODE REVIEW

**Comment by nicain** [comment]
@corbennett When I go to look at the change diff it is HUGE, like basically the whole file, but I cannot spot a lot of differences.  Any idea why this might be?

**Comment by corbennett** [comment]
Yeah. Sorry. I uploaded a new regimen file (small changes) by drag and drop. Turns out this shows up as a wholesale editing of the entire file contents... Won't do that next time!

**Review by nicain — CHANGES_REQUESTED** [review]
@corbennett I found the problem; your text editor added some invisible characters to every line.  Can you get these out of there, and squash this commit?  Happy to help if you need it (this will require a rebase and a force push)

Here is an example (the problem spots are indicated with a ^M):



```
       script_md5: *change_detection_script_md5
-        parameters:
-            <<: *image_set_a_parameters
-            stage: EPHYS_1_images_A
-            warm_up_trials: 2
-            flash_omit_probability: 0.05
-
-    
+^M
+_change_detection_script: &change_detection_script^M
+    http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/change_detection_with_fingerprint.py?at=021ec55fbbdbb05aad1681c016e83066fe5aa1dd^M
+^M
+_change_detection_script_md5: &change_detection_script_md5^M
+    e0535f3b6f03ccc8eeccaed2118f3c1d^M
```

**Comment by corbennett** [comment]
@nicain ok. should be fixed. sorry about that.

**Review by nicain — APPROVED** [review]
LGTM

**Review by nicain — APPROVED** [review]

**Pull request merged**
