### PR TITLE
add 75min duration stages

### PR DESCRIPTION
**Pull request by mochic**
We would like to be able to play behavior for 75 minutes for some stages.

### CODE REVIEW

**Review by jeromelecoq — COMMENTED** [review]
What is the value of passing by this 3ul reward volume in the middle where they see both A and B? That confused me a bit.

**Comment by mochic** [comment]
@jeromelecoq 
It’s just to make sure there’s a transition that leads to it. For manual transitions the to and from stages don’t really matter. Since a manual transition doesn’t do anything differently based on starting stage.

**Comment by jeromelecoq** [comment]
Are these 3 ul just test stages?

**Review by jeromelecoq — APPROVED** [review]

**Comment by mochic** [comment]
@jeromelecoq 
the 3uL stages were added by request of Corbett and some trainers

**Comment by corbennett** [comment]
Yes these are just tests. We will likely remove these in a later regimen update.

**Pull request merged**
