### PR TITLE
fix agent_socket bug

### PR DESCRIPTION
**Pull request by mochic**
We found a parameter bug.

### CODE REVIEW

**Comment by mochic** [comment]
@jeromelecoq 
Hey,
I'm really sorry this keeps coming up but we keep hitting small-ish bugs. I'm confident that we are getting very close to something that won't have any more bugs.

**Comment by jeromelecoq** [comment]
what is this agent_socket: "127.0.0.1:5000  parameter doing? 
Are you overwriting which server it is talking to?

**Comment by mochic** [comment]
@jeromelecoq 
It's a hack we need to employ to polyfill a feature that Ross can hopefully add in later. It points to localhost at port 5000 which should be the agent socket. We use the agent socket to run the replay so that we can use agent's session setup/teardown to submit our behavior output to lims. I put it in a parameter rather than hardcoding it incase of some weird situation where we would need to change it. Port 5000 is the default agent socket for remote method requests.

**Comment by jeromelecoq** [comment]
> @jeromelecoq
> It's a hack we need to employ to polyfill a feature that Ross can hopefully add in later. It points to localhost at port 5000 which should be the agent socket. We use the agent socket to run the replay so that we can use agent's session setup/teardown to submit our behavior output to lims. I put it in a parameter rather than hardcoding it incase of some weird situation where we would need to change it. Port 5000 is the default agent socket for remote method requests.

Sorry can you explain differently? Why do you need this agent to replay a script?

**Comment by mochic** [comment]
so that agent can perform the upload to lims

**Review by jeromelecoq — APPROVED** [review]
This looks hacky. I am happy to approve but again I would be careful with deploying this in production. Given that design and build closure is soon. You probably should look into a more stable implementation.

**Pull request merged**
