### PR TITLE
Enh/75 integration testing 2

### PR DESCRIPTION
**Pull request by mochic**
attempts to address #75
there's still some janky code imbedded throughout and i'm going to quickly change the way progression fixtures and mice fixtures are paired
run it from project root with make integration-test
todo:
- [ ] ~~rework mice fixtures~~
- [x] kill services at end of run
- [ ] ~~use declarative container naming and ferry those to subsequent processes to avoid conflicts~~

### CODE REVIEW

**Comment by mochic** [comment]
@nicain please review when you have time

**Comment by mochic** [comment]
@nicain i think i got carried away with improvements and think this is good enough for now, let me know if you want further improvements

**Review by nicain — APPROVED** [review]
Great work Chris, this looks awesome!

**Comment by mochic** [comment]
@nicain thanks for the review, i think that in the past i was trying to shoehorn docker into some sort of integration test runner role but should have been using python for that all along

**Pull request merged**
