### PR TITLE
update regimen criteria and fix start_stop bug

### PR DESCRIPTION
**Pull request by mochic**
Fixes start_stop bug by applying a value of start_stop_padding of 1 to every stage.

### CODE REVIEW

**Comment by mochic** [comment]
@jeromelecoq 
Hey,
We sorry to bother you with this on Friday but we need to update this regimen to fix a camstim bug and we we're hoping to move mice over to it today. Could you please give this a look?
-Chris

**Comment by corbennett** [comment]
@jeromelecoq Can you take a look at this PR? We'd like to move animals to this regimen today if possible. Thanks!

**Review by jeromelecoq — APPROVED** [review]
looks good

**Comment by jeromelecoq** [comment]
done

**Pull request merged**
